### ISSUE TITLE
不支持Android gradle插件3.0版本

### ISSUE THREAD

**Issue by Chen-Sir** [YamLee/apk-releaser-plugin#4]
不支持Android Gradle插件3.0版本，即无法在Android Studio3.0上使用。
会报错：
Error:(56, 0) Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

解决 ：修改文件名代码请这样写

android.applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "xinlebao_${defaultConfig.versionName}_${releaseTime()}.apk"
                }
            }

希望您能更新下插件版本，方便大家使用。谢谢。

成都钱方Android

**Comment by YamLee** [comment]
近期会更新一下
