### ISSUE TITLE
多渠道打包时，修改了apk文件，没有重新签名

### ISSUE THREAD

**Issue by teejoe** [YamLee/apk-releaser-plugin#6]
你好，阅读了多渠道打包的相关代码，没有看到重新签名的操作，请问是为什么？
在META-INF下面增加文件不会破坏apk的原有签名吗？ 我这边测试增加文件之后apk安装都会报错

**Comment by YamLee** [comment]
当前apk-releaser-plugin只支持v1 签名，在新版Android Gradle编译apk时会默认使用v2 schme签名,在build.gradle配置如下即可正常使用插件打包

```
signingConfigs {
      release {
        v2SigningEnabled false
      }
}
```
